//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPCDatabaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCs101
    {
        public int PCID { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SSD_HDD { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<int> PRICE { get; set; }
    }
}
